# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: "install-dependencies-tbgenkit"
    name: golang:1.24.4
    dir: "tbgenkit"
    waitFor: ["-"]
    env:
      - "GOPATH=/gopath"
    volumes:
      - name: "go"
        path: "/gopath"
    script: |
      go mod tidy

  - id: "run-e2e-tests-tbgenkit"
    name: golang:1.24.4
    dir: "tbgenkit"
    waitFor: ["install-dependencies-tbgenkit"]
    env:
      - "GOPATH=/gopath"
      - TOOLBOX_VERSION=$_TOOLBOX_VERSION
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
      - TOOLBOX_MANIFEST_VERSION=$_TOOLBOX_MANIFEST_VERSION
    volumes:
      - name: "go"
        path: "/gopath"
    script: |
      go test -tags=e2e -coverprofile=coverage-e2e.out -covermode=atomic ./... -v -race

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TOOLBOX_VERSION: '0.26.0'
  _TOOLBOX_MANIFEST_VERSION: '34'
